### ISSUE TITLE
演示环境看不了

### ISSUE THREAD

**Issue by anyangdp** [zhaoyachao/zdh_server#10]
演示环境看不了了。之前看到说要代码会更新，好像还没更新啊

**Comment by zhaoyachao** [comment]
演示环境已恢复,源码目前正在对齐版本,即将更新
&nbsp;


18岁的年华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月26日(星期一) 下午2:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [zhaoyachao/zdh_server] 演示环境看不了 (Issue #10)





 
演示环境看不了了。之前看到说要代码会更新，好像还没更新啊
