### ISSUE TITLE
大佬 提交一段代码 

### ISSUE THREAD

**Issue by gr51** [zhaoyachao/zdh_server#12]
![image](https://github.com/user-attachments/assets/11d473b7-aa29-42dd-b863-18f0eff37382)

web 修改 pom.xml 添加
```

   <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-jdbc</artifactId>
            <version>${hive-jdbc.version}</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>log4j-over-slf4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty.aggregate</groupId>
                    <artifactId>jetty-all</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
        
 WEB的       
DBUtil文件 167 添加

配置了jdbc的hive数据源  
```

            if(url.startsWith("jdbc:hive2")) {


                    preparedStatement = connection.prepareStatement("SHOW TABLES");
                    resultSet = preparedStatement.executeQuery();

                    while (resultSet.next()) {
                        String tableName = resultSet.getString(1); // 表名在第一列
                        result.add(tableName);
                    }
                return result;
            }
```
            
            取数据库表
            
            
            server的
            DataSources 839 修改  （好像这里是别名有问题，直接注释掉了 然后测通了）
`                if (!inPut.toLowerCase.equals("hbase") && !inputOptions.asInstanceOf[Map[String,String]].getOrElse("url","").toLowerCase.contains("jdbc:hive2:")) `
                
                
                
                
                
                
      不知道您哪里实现了 然后测不通hive的jdbc，就自己添加了。 还有一个问题想请教您
![image](https://github.com/user-attachments/assets/c5aac7bd-bb70-497e-b7d8-99753b85d7da)

  当数据源类型为HIVE的时候 server 找不到tableName， 然后我就在Dsi_Info中添加了 ， 又遇到了
![image](https://github.com/user-attachments/assets/d841a459-e34d-4a7b-8cc4-a2842689637f)
我看您hivedatasource 的实现好像用的是spark on hive ，不太清楚也不太懂 这里的配置 ，总之一直找的都是默认的，是不是我服务器要修改一些配置文件 ，让spark启动的的时候能找到hive

**Comment by zhaoyachao** [comment]
感谢反馈, hive类型数据源，需要在spark环境中配置hive，hadoop相关配置文件
