### ISSUE TITLE
server启动后，任务卡着不动

### ISSUE THREAD

**Issue by lwy1111111** [zhaoyachao/zdh_server#5]
server 启动后任务一直显示如下
![image](https://user-images.githubusercontent.com/41666805/116181674-9e97c900-a74d-11eb-934d-6a6ff192b851.png)
web执行任务后，进度一直显示6.5%
![image](https://user-images.githubusercontent.com/41666805/116181886-fcc4ac00-a74d-11eb-90c5-8adc6885e8e3.png)
这是为什么？

**Comment by lwy1111111** [comment]
![image](https://user-images.githubusercontent.com/41666805/116181950-18c84d80-a74e-11eb-882b-fb74f0edcb3d.png)
这是sh启动文件

**Comment by zhaoyachao** [comment]
你看到的只是任务组的进度，任务组的进度表示 这个任务组下的所有子任务的完成度，如果想看具体任务的进度，通过进入子任务界面查看具体的进度和日志，具体为什么卡住 需要通过子任务的日志来分析




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaoyachao/zdh_server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 中午11:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhaoyachao/zdh_server] server启动后，任务卡着不动 (#5)





 
server 启动后任务一直显示如下
 
 web执行任务后，进度一直显示6.5%
 
 这是为什么？
