### ISSUE TITLE
任务运行失败...

### ISSUE THREAD

**Issue by lwy1111111** [zhaoyachao/zdh_server#6]
![image](https://user-images.githubusercontent.com/41666805/116424586-37c0ff80-a874-11eb-9de2-d4a6d2e58f3f.png)
上图中的server就只跑了一个任务，但出现了：调度任务ID:836968828486291456,任务实例ID:836968879132512256,任务执行时间:2021-04-28 22:28:54.0,日志[ERROR]:[调度平台]:[ETL] JOB ,开始发送单源ETL 处理请求,异常请检查zdh_server服务是否正常运行,或者检查网络情况,postRequest -- IO error!的问题。前面有成功过相同的任务。这是为啥啊

**Comment by zhaoyachao** [comment]
请先确定server服务是否正常运行，因个个版本差异较大，建议使用4.7.X 最新版本，若有问题，请尽量说明版本，和日志------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月28日(星期三) 晚上10:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhaoyachao/zdh_server] 任务运行失败... (#6)

**Comment by zhaoyachao** [comment]
请确保web服务和server服务网络正常访问------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月28日(星期三) 晚上10:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhaoyachao/zdh_server] 任务运行失败... (#6)
