### ISSUE TITLE
多源etl使用

### ISSUE THREAD

**Issue by lwy1111111** [zhaoyachao/zdh_server#7]
![image](https://user-images.githubusercontent.com/41666805/116527720-95edf100-a90d-11eb-8a15-8daa37c9154b.png)
请问一下这个功能是怎么使用的

**Comment by zhaoyachao** [comment]
功能使用,参考新增多源任务界面相关介绍




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaoyachao/zdh_server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 下午5:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhaoyachao/zdh_server] 多源etl使用 (#7)





 

 请问一下这个功能是怎么使用的
